config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # CRUD

  # # Create
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  # Read many
  get "tasks", to: "tasks#index"

  # # Read only one
  get "tasks/:id", to: "tasks#show"


  # # Update
  # get "tasks/:id/edit", to: "tasks#edit"
  # patch "tasks/:id", to: "tasks#update"

  # # Delete

  # delete "tasks/:id", to: "tasks#destroy"
  # root to: 'pets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new
    task.title = params[:title]
    task.details = params[:details]
    task.completed = params[:completed]
    task.save

    redirect_to task_path(task)
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<form action="/tasks" method="post">

  <!-- # look into the lecture and add hidden, authentication -->
  <!-- change this form to form for in the note,...follow the note and google a lots -->
  <%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br/>

    <%= f.label :details %>
    <%= f.text_field :details %><br/>

    <%= f.submit %>
  <% end %>

</form>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<%= @tasks.each do |task| %>

  <h2><input type="checkbox"/><%= link_to task.title, tasks_path(task) %></h2>

  <details><p> Do not mix colors </p></details>
  <p><%= task.completed %></p>
  <%= link_to "Back to list", tasks_path(task) %>
<% end %>


<!--
    <div>
        <input type="checkbox" id="scales" name="feature"
               value="scales" checked />
        <label for="scales">Scales</label>
    </div>

  <input type="checkbox" name="title1" value="Laundry"> Do not mix colors<br>
  <input type="checkbox" name="title2" value="Studying"> A lot of flashcards to do<br>


  Task.create(title: 'Laundry', details: 'Do not mix colors!')
  Task.create(title: 'Studying', details: 'A lot of flashcards to do', completed: true)

  <input type="checkbox" title="Laundry" />
 -->
  <!-- <details>
  <summary>Copyright 1999-2018.</summary>
  <p> - by Refsnes Data. All Rights Reserved.</p>
  <p>All content and graphics on this web site are the property of the company Refsnes Data.</p>
</details>
 -->

app/views/tasks/new.html.erb
<form action="/tasks" method="post">

  <!-- # look into the lecture and add hidden, authentication -->
  <!-- change this form to form for in the note,...follow the note and google a lots -->
  <%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br/>

    <%= f.label :details %>
    <%= f.text_field :details %><br/>

    <%= f.submit %>
  <% end %>

</form>




<!--
  <label for="title">Enter a name</label>
  <input type="text" title="task[title]"><br/>

  <label for="title">Enter  details</label>
  <input type="text" title="task[details]"><br/>

  <label for="title">Enter a completed</label>
  <input type="text" title="task[completed]"><br/>

  <input type="submit">
 -->

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to "Back to all tasks", tasks_path %>